[toolchain]
anchor_version = "0.30.1"    # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.17"    # Solana version to use(applies to all Solana tools)

[features]
seeds = true
skip-lint = false

[programs.localnet]
contract = "4EcsuyVt14SfaZWWQwCnVRf7SsioVzVrxMNynHx7oGd8"

[programs.devnet]
contract = "BzDes2xKWJVckSZ7yp16ouch5LpQ88rEPATbTf4UcX7T"

[programs.mainnet]
contract = "BzDes2xKWJVckSZ7yp16ouch5LpQ88rEPATbTf4UcX7T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deploy_wallet/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"

[test]
startup_wait = 20000